metric:
  _target_: submodules.EvalMuseMini.metric.ElementAlignmentMetric
  dataset_dir: /home/naumov/code/general-pipeline/data/generated_images/stable-diffusion-v1-5-stable-diffusion-v1-5/3/
data_file: /home/naumov/code/general-pipeline/data/generated_images/stable-diffusion-v1-5-stable-diffusion-v1-5/3/metadata.json
model_path: /home/naumov/code/general-pipeline/submodules/EvalMuseMini/pretrained_models/fga_blip2.pth