include:
  - monitoring/compose.yml

services:
  fundamental-metric:
    build:
      context: ./submodules/fundamental_metrics/
      tags: 
        - "fundamental-metrics:main"
    container_name: fundamental-metrics
    network_mode: host
    volumes:
      - ./results:/results

  diffusion-engine:
    build:
      context: ./submodules/DiffusionEngine/
      tags: 
        - "diffusion-engine:main"
    container_name: diffusion-engine 
    network_mode: host
    volumes:
      - ./data:/data
