include:
  - monitoring/compose.yml

x-defaults: &defaults
  network_mode: host
  runtime: nvidia
  environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=compute,utility
  
services:
  diffusion-engine:
    build:
      context: ./submodules/DiffusionEngine/
      tags: 
        - "diffusion-engine:main"
    container_name: diffusion-engine 
    volumes:
      - ./data/generated_images:images
      
    <<: *defaults
    
  fundamental-metrics:
    build:
      context: ./submodules/fundamental_metrics/
      tags: 
        - "fundamental-metrics:main"
    container_name: fundamental-metrics
    depends_on:
      diffusion-engine:
        condition: service_completed_successfully
    volumes:
     - ./data:images:ro
     - ./results:results
     
     <<: *defaults

  qualiclip:
    build:
      context: ./submodules/QualiClip
      tags: 
        - "qualiclip:main"
    container_name: qualiclip
    depends_on:
      diffusion-engine:
        condition: service_completed_successfully
    volumes:
     - ./data:images:ro
     - ./results:results

     <<: *defaults

volumes:
  images:
  results:
