include:
  - monitoring/compose.yml

services:
  diffusion-engine:
    build:
      context: ./submodules/DiffusionEngine/
      tags: 
        - "diffusion-engine:main"
    container_name: diffusion-engine 
    network_mode: host
    volumes:
      - ./data/generated_images:images

  fundamental-metrics:
    build:
      context: ./submodules/fundamental_metrics/
      tags: 
        - "fundamental-metrics:main"
    container_name: fundamental-metrics
    network_mode: host
    depends_on:
      diffusion-engine:
        condition: service_completed_successfully
    volumes:
     - ./data:images:ro
     - ./results:results

volumes:
  images:
  results: