defaults:
  - metrics/clip_score@clip  # Load CLIP config
  - metrics/fid_score@fid    # Load FID config
  - metrics/inception_score@inception
  - _self_

clip:
  _target_: submodules.fundamental_metrics.metrics.clip_score.CLIPSimilarity
  mode: text_image
  model_name: ViT-B/32

fid:
  _target_: submodules.fundamental_metrics.metrics.fid_score.FIDMetric
  feature: 2048

inception:
  _target_: submodules.fundamental_metrics.metrics.inception_score.InceptionScoreMetric